// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_completedLevel = new UnifiedAchievement("CompletedLevel",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "grp.spilgames.tappyplane.completedlevel"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "CompletedLevel"
#endif
            );

        public static UnifiedAchievement CompletedLevel
        {
            get { return s_completedLevel; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_completedLevel,
        };
    }
}
